title: Artur Szalak
description: Personal website and career portfolio
baseurl: "/harimau"
url: "https://harimau-airene.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  style: compressed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/ 